# Generated by Django 4.0.5 on 2022-07-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulimapp', '0002_alter_feeds_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
