# Generated by Django 4.0.5 on 2022-07-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulimapp', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='is_farmer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
